Add posts resolvers and endpoints
pckv/repost-fastapi pull request #11
Opened 2020-02-04 12:06 UTC by EspenK

Resolves #3

2020-02-04 13:45 UTC, jonsondrem approved these changes

2020-02-04 18:00 UTC, pckv requested changes

2020-02-04 18:00 UTC, pckv commented on repost/api/routes/posts.py
> +from repost.api.schemas.post import CreatePost, Post
Move these to schemas package (add to __init__.py)

2020-02-05 11:07 UTC, pckv approved these changes
Now it looks professional

2020-02-05 11:07 UTC, merged