Change schema to use name and models to use id
pckv/repost-fastapi pull request #36
Opened 2020-02-08 15:44 UTC by EspenK

Change some stuff that was done in [this commit](https://github.com/pckv/repost-fastapi/pull/33/commits/22374a50943d16e710eba49359915523258fe54f).

2020-02-08 15:58 UTC, pckv approved these changes
Looks good. The database should use the ID as reference, even if the API schema identifies by name for User and Resub. Conversion can be done in the CRUD functions by using the relationships in the model.

2020-02-09 14:32 UTC, jonsondrem commented on repost/models/comment.py
> +    author_id = Column(String, ForeignKey('users.id'))
Change from String to Integer

2020-02-09 14:33 UTC, jonsondrem commented on repost/models/comment.py
> +    parent_resub_id = Column(String, ForeignKey('resubs.id'))
Change from String to Integer

2020-02-09 14:33 UTC, jonsondrem commented on repost/models/comment.py
> +    parent_post_id = Column(String, ForeignKey('posts.id'))
Change from String to Integer

2020-02-09 14:33 UTC, jonsondrem commented on repost/models/post.py
> +    author_id = Column(String, ForeignKey('users.id'))
Change from String to Integer

2020-02-09 14:33 UTC, jonsondrem commented on repost/models/post.py
> +    parent_resub_id = Column(String, ForeignKey('resubs.id'))
Change from String to Integer

2020-02-09 14:33 UTC, jonsondrem requested changes
Some strings need to be changed to Integer if they are to be changed from name to id

2020-02-09 16:17 UTC, pckv commented
> Some strings need to be changed to Integer if they are to be changed from name to id

Nice catch! Fixed with 2811cd9d7cd869f78b5cb4c6afd5bf37c3094b2e

2020-02-09 16:30 UTC, jonsondrem approved these changes
:+1:

2020-02-09 16:37 UTC, merged